#!/usr/bin/env bash

if [ "$1" == "up" ]; then
    #if [ ! -f docker/php/ssh/id_rsa ] && [ ! -f docker/php/ssh/id_rsa.pub ]; then
    #if [ ! -d docker/php/ssh ]; then
    #    mkdir -p docker/php/ssh
    #    cp ~/.ssh/id_rsa docker/php/ssh/
    #    cp ~/.ssh/id_rsa.pub docker/php/ssh/
    #fi
    docker-compose "$@"
elif [ "$1" == "enter-root" ]; then
    docker-compose exec php /bin/zsh
elif [ "$1" == "enter" ]; then
    docker-compose exec -u utente php /bin/zsh
elif [ $# -gt 0 ]; then
    docker-compose "$@"
else
    docker-compose ps
fi
