version: '3.7'

volumes:
  app_database:
  app_cache: {}

networks:
  my_app_net:
    driver: bridge
    name: my_app_net

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/symfony-4.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
    networks:
      - my_app_net

  php:
    build: ./docker/php
    hostname: app_hostname
    volumes:
      - ./:/var/www/app
      - ./docker/data/shell_history:/home/utente/shell_history
    networks:
      - my_app_net
    environment:
      - HISTFILE=/home/utente/shell_history/.zsh_history

  servicedb:
    image: mysql:5.7
    #restart: always
    volumes:
      - app_database:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    #- MYSQL_DATABASE=adrias_web
    ports:
      - '3307:3306'
    command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
    networks:
      - my_app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - servicedb
    environment:
      - PMA_HOST=servicedb
    networks:
      - my_app_net

  servicememcached:
    image: memcached:latest
    volumes:
      - app_cache:/var/lib/memcached
    networks:
      - my_app_net
