version: '3'

volumes:
  app_database:
  app_cache: {}

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/symfony-4.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
  php:
    build: ./docker/php
    hostname: app_hostname
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV=${APP_ENV}

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - app_database:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    ports:
      - '3307:3306'
    command: mysqld --sql_mode="" #Per mysql, non serve per mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - PMA_HOST=database

  servicememcached:
    image: memcached:latest
    volumes:
      - app_cache:/var/lib/memcached
