parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BoundedContextToRename\Shared\Infrastructure\Communication\Http\Symfony\Controller\:
    resource: '%kernel.project_dir%/src/BoundedContextToRename/Shared/Infrastructure/Communication/Http/Symfony/Controller/*'
    tags: ['controller.service_arguments']
