version: '3.8'

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  known_hosts:
    file: ~/.ssh/known_hosts

services:

  nginx:
    ports:
      - "8080:80"

  servicedb:
    ports:
      - "3311:3306"