version: '3.7'

volumes:
  #  app_memcached: {}
  app_database: {}

networks:
  app_net:
    driver: bridge
    name: app_net

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php_app
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ../:/var/www/app
      - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net

  php_app:
    build: php
    hostname: app_hostname
    volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - app_net
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
    secrets:
      - source: id_rsa
        target: /home/utente/.ssh/id_rsa
      - source: id_rsa.pub
        target: /home/utente/.ssh/id_rsa.pub
      - source: known_hosts
        target: /home/utente/.ssh/known_hosts

  servicedb:
    image: mariadb:10.3.22
    volumes:
      - app_database:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    networks:
      - app_net

  nodejs:
    build: nodejs
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    networks:
      - app_net
