parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Project\Common\Infrastructure\Communication\Http\Symfony\Controller\:
    resource: '%kernel.project_dir%/src/Project/Common/Infrastructure/Communication/Http/Symfony/Controller/*'
    tags: ['controller.service_arguments']
